version: '3'
services:
  database:

  database:
      image: mariadb:10
      environment:
        - MYSQL_USER=hackmd
        - MYSQL_PASSWORD=hackmdpass
        - MYSQL_DATABASE=hackmd
        - MYSQL_ALLOW_EMPTY_PASSWORD=true
      volumes:
        - database:/var/lib/mysql
        - ./resources/utf8.cnf:/etc/mysql/conf.d/utf8.cnf
      networks:
        backend:
      restart: always

  app:
    image: yagi5/hackmd:latest
    environment:
      - HMD_DB_URL=mysql://hackmd:hackmdpass@database:3306/hackmd
    ports:
      - "0.0.0.0:3000:3000"
    networks:
      backend:
    restart: always
    depends_on:
      - database

networks:
  backend:

volumes:
  database:
